// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://tuhiarimuvrqczjjuwfo.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR1aGlhcmltdXZycWN6amp1d2ZvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzE1MzY0NjMsImV4cCI6MjA0NzExMjQ2M30.Q-dCjvw32wgrBiwt1Ca7hXH6UxtNdro33iQxl1bF2q8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);